"""Command-line entry point for AI Study Assistant.

Exposed as the ``ai-study-assistant`` console script:

- ``ai-study-assistant serve``   start the backend (and the bundled web UI)
- ``ai-study-assistant init``    create .env and the working directories
- ``ai-study-assistant check``   verify the environment and dependencies
- ``ai-study-assistant --version``
"""

from __future__ import annotations

import argparse
import importlib.util
import shutil
import sys
from pathlib import Path

from backend import __version__

CORE_DEPENDENCIES = {
    "fastapi": "fastapi",
    "uvicorn": "uvicorn",
    "dotenv": "python-dotenv",
    "sentence_transformers": "sentence-transformers",
    "sklearn": "scikit-learn",
    "pypdf": "pypdf",
    "multipart": "python-multipart",
    "faiss": "faiss-cpu",
    "langgraph": "langgraph",
    "sqlalchemy": "SQLAlchemy",
    "psycopg": "psycopg[binary]",
}

# Minimal working configuration for `init` when no full .env.example is available
# (pip-installed usage). The source repository ships the complete .env.example.
MINIMAL_ENV_TEMPLATE = """\
# AI Study Assistant configuration (generated by `ai-study-assistant init`).
# See https://github.com/ZQR1101/ai-agent-study-assistant for the full option list.

# Any OpenAI-compatible chat provider works. DeepSeek example:
DEEPSEEK_API_KEY=your_api_key_here
DEEPSEEK_BASE_URL=https://api.deepseek.com
DEEPSEEK_MODEL=deepseek-v4-pro

# Set a real key above; offline tests work without one, LLM calls need it.
ENABLE_LLM_JUDGE=true

# Local RAG (FAISS + sentence-transformers). The embedding model downloads
# from Hugging Face on first use unless EMBEDDING_MODEL_PATH points at a local copy.
EMBEDDING_MODEL_LOCAL_ONLY=false
ENABLE_RAG_AUTO_BUILD=true

# Three-layer learning memory and optional reranker.
ENABLE_MEMORY=false
ENABLE_RERANKER=false
QUERY_REWRITE_MODE=off

# Human-in-the-loop tool approval keys (must differ, >=32 chars each).
ENABLE_INSECURE_DEV_TOOL_KEYS=false
TOOL_APPROVAL_KEY=replace-with-a-long-random-requester-secret
TOOL_APPROVER_KEY=replace-with-a-different-long-random-approver-secret
"""

WORKING_DIRS = ("docs", "rag_index", "data", "logs")


def _print_result(status: str, message: str) -> None:
    print(f"[{status}] {message}")


def _resolve_project_root() -> Path:
    from backend.config import PROJECT_ROOT

    return PROJECT_ROOT


def cmd_serve(args: argparse.Namespace) -> int:
    import uvicorn

    root = _resolve_project_root()
    _print_result("INFO", f"Project root: {root}")
    _print_result(
        "INFO",
        f"Starting AI Study Assistant on http://{args.host}:{args.port} "
        "(API docs at /docs)...",
    )
    uvicorn.run(
        "backend.server:app",
        host=args.host,
        port=args.port,
        reload=args.reload,
    )
    return 0


def _find_env_example() -> Path | None:
    candidates = [
        _resolve_project_root() / ".env.example",
        Path(__file__).parent / "env.example",
    ]
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    return None


def cmd_init(args: argparse.Namespace) -> int:
    root = _resolve_project_root()
    env_file = root / ".env"

    if env_file.exists() and not args.force:
        _print_result("SKIP", f".env already exists: {env_file}")
    else:
        env_example = _find_env_example()
        if env_example is not None:
            shutil.copyfile(env_example, env_file)
            _print_result("OK", f"Created .env from {env_example.name}: {env_file}")
        else:
            env_file.write_text(MINIMAL_ENV_TEMPLATE, encoding="utf-8")
            _print_result("OK", f"Created .env with a minimal template: {env_file}")
        _print_result("HINT", "Edit .env and set a real model API key before chatting.")

    for name in WORKING_DIRS:
        target = root / name
        if target.exists():
            _print_result("SKIP", f"{name}/ already exists")
        else:
            target.mkdir(parents=True, exist_ok=True)
            _print_result("OK", f"Created {name}/")

    static_dir = Path(__file__).parent / "static"
    if static_dir.is_dir():
        _print_result("OK", f"Web UI bundled at {static_dir}")
    else:
        _print_result(
            "INFO",
            "Web UI static files are not bundled (development checkout). "
            "Run `npm install && npm run build`, or use `npm run dev` while developing.",
        )

    _print_result("OK", "Init complete. Start the app with: ai-study-assistant serve")
    return 0


def cmd_check(_args: argparse.Namespace) -> int:
    ok = True

    version = sys.version_info
    python_ok = version >= (3, 11)
    _print_result(
        "OK" if python_ok else "ERROR",
        f"Python {version.major}.{version.minor}.{version.micro}",
    )
    ok &= python_ok

    missing = [
        package
        for module, package in CORE_DEPENDENCIES.items()
        if importlib.util.find_spec(module) is None
    ]
    if missing:
        _print_result("ERROR", f"Missing dependencies: {', '.join(missing)}")
        _print_result("HINT", "Run: pip install ai-study-assistant")
        ok = False
    else:
        _print_result("OK", "All core dependencies are importable")

    try:
        from backend.config import get_config

        config = get_config()
        _print_result("OK", f"Config loaded; model={config.model}")
        _print_result("INFO", f"Project root: {config.project_root}")
        _print_result("INFO", f"Docs dir: {config.docs_path}")
        _print_result("INFO", f"RAG index dir: {config.rag_index_dir}")
        if config.has_api_key:
            _print_result("OK", f"Model API key configured via {config.api_key_source}")
        else:
            _print_result("WARN", "No model API key; offline features work, LLM calls fail")
    except Exception as error:  # noqa: BLE001 - report any config failure
        _print_result("ERROR", f"Cannot load backend.config: {error}")
        return 1

    try:
        import backend.server  # noqa: F401

        _print_result("OK", "backend.server imports cleanly")
    except Exception as error:  # noqa: BLE001
        _print_result("ERROR", f"Cannot import backend.server: {error}")
        ok = False

    root = _resolve_project_root()
    index_file = root / "rag_index" / "index.faiss"
    if index_file.exists():
        _print_result("OK", "RAG index present")
    else:
        _print_result(
            "WARN",
            "RAG index not built yet; it is created automatically on first vector search "
            "(or POST /rebuild-index)",
        )

    if Path(__file__).parent.joinpath("static").is_dir():
        _print_result("OK", "Web UI static files bundled")
    else:
        _print_result("INFO", "Web UI static files not bundled; API-only mode")

    _print_result("OK" if ok else "ERROR", "Check finished")
    return 0 if ok else 1


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="ai-study-assistant",
        description="AI Study Assistant: local web app + CLI for study-focused RAG, agents and memory.",
    )
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")

    subparsers = parser.add_subparsers(dest="command", required=True)

    serve = subparsers.add_parser("serve", help="Start the backend and bundled web UI")
    serve.add_argument("--host", default="127.0.0.1", help="Bind address (default: 127.0.0.1)")
    serve.add_argument("--port", type=int, default=8000, help="Port (default: 8000)")
    serve.add_argument("--reload", action="store_true", help="Enable auto-reload (development)")
    serve.set_defaults(func=cmd_serve)

    init = subparsers.add_parser("init", help="Create .env and working directories")
    init.add_argument("--force", action="store_true", help="Overwrite an existing .env")
    init.set_defaults(func=cmd_init)

    check = subparsers.add_parser("check", help="Verify environment and dependencies")
    check.set_defaults(func=cmd_check)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
